FROM debian:stretch-slim
MAINTAINER mbrooks

RUN apt-get update && \
    apt-get install -y pkg-config liblz4-1 ca-certificates && \
    apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data
COPY journalbeat journalbeat.yml entrypoint /
RUN chmod 0755 /entrypoint /journalbeat

ENTRYPOINT ["/entrypoint"]
